services:
  db:
    image: mariadb:10.11
    container_name: fox_shelter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword123!
      MYSQL_DATABASE: FoxShelterDB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pRootPassword123!"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: fox_shelter_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=FoxShelterDB;Uid=root;Pwd=RootPassword123!;
      - Jwt__Secret=FoxShelter_Cheie_Super_Secreta_Si_Lunga_2026!
      - Jwt__Issuer=FoxShelterAPI
      - Jwt__Audience=FoxShelterFrontend

volumes:
  db_data: