events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;
        # Redirectionam traficul HTTP simplu catre HTTPS
        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        # Citeste certificatele din volumul Docker
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        location / {
            # Trimite traficul catre containerul API pe portul standard HTTP de .NET 8
            proxy_pass http://fox_shelter_api:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}