events {
    worker_connections 1024;
}

http {
    # tipurile de fișiere (ex: să știe că .jpg e imagine, nu text)
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;
        # HTTP catre HTTPS
        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        # rezolvarea certificatelor web - local
        ssl_certificate     /etc/nginx/certs/localhost.pem;
        ssl_certificate_key /etc/nginx/certs/localhost-key.pem;

        # interceptarea cererilor HTTP accidentale pe port HTTPS
        error_page 497 https://$host:8443$request_uri;

        # 1. GESTIONAREA IMAGINILOR (Corectată absolut)
        location /uploads/ {
            # Linia critică: Nginx caută la aceeași cale de bază ca și C#
            root /app/wwwroot;
            access_log off;
            expires max;
            add_header Cache-Control "public";
        }

        # 2. API - Trimiterea traficului către backend-ul .NET
        location / {
            proxy_pass http://fox_shelter_api:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}